package org.ria.ifzz.RiaApp.service;

import org.ria.ifzz.RiaApp.domain.*;
import org.ria.ifzz.RiaApp.repository.ControlCurveRepository;
import org.ria.ifzz.RiaApp.utils.*;
import org.springframework.web.bind.annotation.RestController;

import javax.validation.constraints.NotNull;
import java.io.IOException;
import java.util.ArrayList;
import java.util.List;

import static org.ria.ifzz.RiaApp.domain.HormonesPattern.CORTISOL_PATTERN;

@RestController
public class ResultService {

    private final CustomFileReader customFileReader;
    private final CountResultUtil countResultUtil;
    private final FileUtils fileUtils;
    private final ControlCurveRepository controlCurveRepository;
    private final ControlCurveService controlCurveService;
    private final DataAssigner dataAssigner;

    public ResultService(CustomFileReader customFileReader, CountResultUtil countResultUtil, FileUtils fileUtils, ControlCurveRepository controlCurveRepository, ControlCurveService controlCurveService, DataAssigner dataAssigner) {
        this.customFileReader = customFileReader;
        this.countResultUtil = countResultUtil;
        this.fileUtils = fileUtils;
        this.controlCurveRepository = controlCurveRepository;
        this.controlCurveService = controlCurveService;
        this.dataAssigner = dataAssigner;
    }

    /**
     * takes file store in local disc space
     *
     * @param model data from uploaded file
     * @return expected List of Strings
     * @throws IOException
     */
    public List<String> getFileData(DataFileMetadata model) throws IOException {
        System.out.println(customFileReader.getUploadComment());
        List<String> streamRead = customFileReader.readFromStream(model);
        return streamRead;
    }

    /**
     * takes fileName of upload file and set specific id for each entities
     * reads given Strings List and create Result entity for each lines of given,
     *
     * @param fileData pre-cleaned list
     * @param file
     * @return Result entities
     */
    public List<Result> setResultFromColumnsLength(List<String> fileData,
                                                   @NotNull DataFileMetadata file,
                                                   Backlog backlog) {

        Result result = new Result();
        List<Result> results = new ArrayList<>();
        for (String line : fileData) {
            if (line.startsWith(" \tUnk")) {
                result = new Result();
                result.setFileName(fileData.indexOf(line) + "_" + fileUtils.setFileName(file));
                result.setBacklog(backlog);
                results.add(result);
            }
        }
        return results;
    }

    /**
     * find Result entity in database by {@code}fileName_index,
     * which is created by file's fileName + _ + index, and
     * then assign results from "CCMP" table
     *
     * @param fileData generated by upload file
     */
    public List<Result> assignDataToResult(List<String> fileData,
                                           FileEntity fileEntity,
                                           List<Result> results) {
        String fileId = fileEntity.getDataId();
        List<Result> resultsWithData = new ArrayList<>();
        List<Result> resultList = new ArrayList<>();

        resultsWithData = dataAssigner.setCpm(fileData, results);
        for (int i = 0; i < resultsWithData.size(); i++) {
            Result result = resultsWithData.get(i);
            resultList.add(result);
        }

        resultsWithData = dataAssigner.setPosition(fileData, results);
        for (int i = 0; i < resultsWithData.size(); i++) {
            Result result = resultsWithData.get(i);
            resultList.add(result);
        }

        resultsWithData = dataAssigner.setSamples(fileData, fileId, results);
        for (int i = 0; i < resultsWithData.size(); i++) {
            Result result = resultsWithData.get(i);
            resultList.add(result);
        }
            System.out.println("resultsWithData size: " + resultList.size());
        return resultList;
    }

    private void setStandardPattern(List<String> fileData) {
        // get standard pattern
        System.out.println("Pattern detected:");
        if (fileData.get(0).equals("KORTYZOL_5_MIN")) {
            System.out.println(fileData.get(0));
            countResultUtil.logDose(CORTISOL_PATTERN);
        }
    }

    private void setBindingPercent(List<Double> curve, List<Point> points, List<ControlCurve> controlCurveList) {
        setControlPointsFromControlCurve(controlCurveList, curve, points);
        countResultUtil.setControlCurveCpmWithFlag(points);
        countResultUtil.setStandardsCpmWithFlags(points);
        countResultUtil.bindingPercent();
    }

    /**
     * @param fileData         contains data which will be assign to Result
     * @param controlCurveList curve points
     * @param results          list of the Result entities with assigned data
     * @return list of Result entities with calculated mass of the hormone in nanograms
     */
    public List<Result> assignNgPerMl(List<String> fileData,
                                      List<ControlCurve> controlCurveList,
                                      List<Result> results) {

        List<Point> points = new ArrayList<>();
        List<Double> curve = new ArrayList<>();
        setStandardPattern(fileData);
        setBindingPercent(curve, points, controlCurveList);
        countResultUtil.logarithmRealZero();
        countResultUtil.countRegressionParameterB();
        countResultUtil.countRegressionParameterA();
        return getCountedResults(fileData, results);
    }

    private List<Result> getCountedResults(List<String> list, List<Result> results) {
        List<Result> countedResults = new ArrayList<>();
        for (int i = 25; i < list.size(); i++) {
            Result result = results.get(i);
            double point = result.getCpm();
            System.out.println("Point CPM: " + point);
            double counted = countResultUtil.countResult(point);
            if (Double.isNaN(counted)) {
                counted = 0.0;
            }
            result.setNg(counted);
            countedResults.add(result);
        }
        return countedResults;
    }

    private void setControlPointsFromControlCurve(List<ControlCurve> controlCurveList,
                                                  List<Double> curve,
                                                  List<Point> points) {
        ControlCurve controlCurve;
        //set cpm values to control curve points
        for (int i = 0; i < 24; i++) {
            controlCurve = controlCurveList.get(i);
            Double pointValue = controlCurve.getCpm();
            Boolean flag = controlCurve.isFlagged();
            curve.add(pointValue);
            Point point = new Point(pointValue, flag);
            points.add(point);
        }
    }


    public List<Result> setDataToResult(@NotNull DataFileMetadata file,
                                        List<String> fileData,
                                        Backlog backlog,
                                        FileEntity fileEntity) {

        List<Result> resultsWithData = new ArrayList<>();
        List<Result> resultListWithNg = new ArrayList<>();
        List<ControlCurve> controlCurveList;
        List<ControlCurve> controlCurveListWithData;
        List<Result> results = setResultFromColumnsLength(fileData, file, backlog);

        if (fileData.size() > 24) {
            try {
                resultsWithData = assignDataToResult(fileData, fileEntity, results);
            } catch (Exception e) {
                System.out.println("Assign Data To Result: " + e.getMessage() + " | " + e.getCause());
            }
        }
        controlCurveList = controlCurveService.setControlCurveFromFileData(fileData, file, backlog);
        controlCurveListWithData = controlCurveService.setDataToControlCurve(fileData, fileEntity, controlCurveList);

        //Check if any of standard points are above Zeros points
        if (isStandardCpmAboveZero(controlCurveListWithData)) {
            List<Point> points = new ArrayList<>();
            List<Double> curve = new ArrayList<>();
            setBindingPercent(curve, points, controlCurveList);
            countResultUtil.logarithmRealZero();
            controlCurveRepository.saveAll(controlCurveListWithData);
            return resultsWithData;
        }
        //is they aren't ng will be set to results
        else {

            try {
                resultListWithNg = assignNgPerMl(fileData, controlCurveListWithData, resultsWithData);
            } catch (Exception e) {
                System.out.println("Exception ng: " + e.getMessage() + " with cause: " + e.getCause());
            }
            controlCurveRepository.saveAll(controlCurveListWithData);
            return resultListWithNg;
        }
    }

    /**
     * @param controlCurves list of curve points
     * @return false if any controlCurve points is not flagged (is false),
     * and true if any from those are flagged
     */
    private boolean isStandardCpmAboveZero(List<ControlCurve> controlCurves) {
        boolean checker = false;
        boolean isAbove;
        new ControlCurve();
        ControlCurve controlCurve;
        for (int i = 8; i < 21; i++) {
            controlCurve = controlCurves.get(i);
            if (controlCurve.isFlagged()) {
                checker = true;
                System.out.println("Standard point with ID: " + controlCurve.getId() + " with CPM value " + controlCurve.getCpm() + " are above zero ");
            }
        }
        isAbove = checker;
        return isAbove;
    }
}

