//types for FILE ENTITY ACTIONS
export const GET_FILE_ENTITY = "GET_FILE_ENTITY";
export const GET_FILE_ENTITIES = "GET_FILE_ENTITIES";
export const DELETE_FILE_ENTITY = "DELETE_FILE_ENTITY";

//types for FILE DATA ACTIONS
export const GET_BACKLOG = "GET_BACKLOG";
export const GET_BACKLOG_CC = "GET_BACKLOG_CC";
export const GET_GRAPH_CURVE = "GET_GRAPH_CURVE";

//types for RESULT ACTIONS
export const GET_RESULT = "GET_RESULT";

//types for CONTROL_CURVE ACTIONS
export const GET_CONTROL_CURVE = "GET_CONTROL_CURVE";

//types for GET_GRAPH_CURVE_POINT ACTIONS
export const GET_GRAPH_CURVE_POINT = "GET_GRAPH_CURVE_POINT";

export const GET_ERRORS = "GET_ERRORS";
