//types for FILE ENTITY ACTIONS
export const GET_EXAMINATION_POINTS = "GET_EXAMINATION_POINTS";
export const DELETE_EXAMINATION_POINT = "DELETE_EXAMINATION_POINT";

//types for CONTROL_CURVE ACTIONS
export const GET_CONTROL_CURVES = "GET_CONTROL_CURVES";

//types for GET_GRAPH_CURVE_LINE ACTIONS
export const GET_GRAPH = "GET_GRAPH";

//types for GET_GRAPH_CURVE_LINE ACTIONS
export const GET_GRAPH_LINE = "GET_GRAPH_LINE";

export const GET_ERRORS = "GET_ERRORS";

//Types for USER
export const SET_CURRENT_USER = "SET_CURRENT_USER";
